# Generated by Django 5.2 on 2025-12-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='Chemical Name (English)', max_length=255, verbose_name='化学品英文名')),
                ('name_jp', models.CharField(help_text='化学物質名（日本語）', max_length=255, verbose_name='化学品日文名')),
                ('cas_number', models.CharField(max_length=20, verbose_name='CAS号')),
                ('sds_threshold', models.FloatField(blank=True, help_text='通知対象物質の裾切値 (例: 0.1)', null=True, verbose_name='SDS阈值 (%)')),
                ('label_threshold', models.FloatField(blank=True, help_text='表示対象物質の裾切値 (例: 1.0)', null=True, verbose_name='标签阈值 (%)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
    ]
